# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 199)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Diametr_out = QtWidgets.QTextBrowser(self.centralwidget)
        self.Diametr_out.setGeometry(QtCore.QRect(330, 10, 81, 51))
        self.Diametr_out.setMaximumSize(QtCore.QSize(81, 51))
        self.Diametr_out.setObjectName("Diametr_out")
        self.Button_Diametr = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Diametr.setGeometry(QtCore.QRect(200, 10, 121, 51))
        self.Button_Diametr.setObjectName("Button_Diametr")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 81, 51))
        self.label_2.setObjectName("label_2")
        self.Sechenie_Out = QtWidgets.QTextBrowser(self.centralwidget)
        self.Sechenie_Out.setGeometry(QtCore.QRect(330, 70, 81, 51))
        self.Sechenie_Out.setMaximumSize(QtCore.QSize(81, 51))
        self.Sechenie_Out.setObjectName("Sechenie_Out")
        self.Button_Sechenie = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Sechenie.setGeometry(QtCore.QRect(200, 70, 121, 51))
        self.Button_Sechenie.setObjectName("Button_Sechenie")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 81, 51))
        self.label_3.setObjectName("label_3")
        self.Sechenie_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Sechenie_input.setGeometry(QtCore.QRect(102, 11, 91, 51))
        self.Sechenie_input.setText("")
        self.Sechenie_input.setObjectName("Sechenie_input")
        self.Diametr_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Diametr_input.setGeometry(QtCore.QRect(100, 70, 91, 51))
        self.Diametr_input.setText("")
        self.Diametr_input.setObjectName("Diametr_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конвектор_v.0.1"))
        self.Button_Diametr.setText(_translate("MainWindow", "Диаметр"))
        self.label_2.setText(_translate("MainWindow", "Сечение"))
        self.Button_Sechenie.setText(_translate("MainWindow", "Сечение"))
        self.label_3.setText(_translate("MainWindow", "Диаметр"))
        self.menu.setTitle(_translate("MainWindow", "диаметр/сечение"))
        self.menu_2.setTitle(_translate("MainWindow", " "))
